export const TARGET_LANGUAGES = [
  { value: "af", label: "Afrikaans" },
  { value: "sq", label: "Albanian" },
  { value: "am", label: "Amharic" },
  { value: "ar", label: "Arabic" },
  { value: "ar-DZ", label: "Arabic (Algeria)" },
  { value: "ar-EG", label: "Arabic (Egypt)" },
  { value: "ar-IQ", label: "Arabic (Iraq)" },
  { value: "ar-JO", label: "Arabic (Jordan)" },
  { value: "ar-KW", label: "Arabic (Kuwait)" },
  { value: "ar-LB", label: "Arabic (Lebanon)" },
  { value: "ar-LY", label: "Arabic (Libya)" },
  { value: "ar-MA", label: "Arabic (Morocco)" },
  { value: "ar-OM", label: "Arabic (Oman)" },
  { value: "ar-QA", label: "Arabic (Qatar)" },
  { value: "ar-SA", label: "Arabic (Saudi Arabia)" },
  { value: "ar-SY", label: "Arabic (Syria)" },
  { value: "ar-TN", label: "Arabic (Tunisia)" },
  { value: "ar-AE", label: "Arabic (UAE)" },
  { value: "ar-YE", label: "Arabic (Yemen)" },
  { value: "hy", label: "Armenian" },
  { value: "as", label: "Assamese" },
  { value: "az", label: "Azerbaijani" },
  { value: "bn", label: "Bengali" },
  { value: "bn-BD", label: "Bengali (Bangladesh)" },
  { value: "bn-IN", label: "Bengali (India)" },
  { value: "bs", label: "Bosnian" },
  { value: "bg", label: "Bulgarian" },
  { value: "my", label: "Burmese" },
  { value: "ca", label: "Catalan" },
  { value: "zh", label: "Chinese (Simplified)" },
  { value: "zh-TW", label: "Chinese (Traditional)" },
  { value: "zh-HK", label: "Chinese (Cantonese)" },
  { value: "hr", label: "Croatian" },
  { value: "cs", label: "Czech" },
  { value: "da", label: "Danish" },
  { value: "nl", label: "Dutch" },
  { value: "nl-BE", label: "Dutch (Belgium)" },
  { value: "en", label: "English" },
  { value: "en-AU", label: "English (Australia)" },
  { value: "en-CA", label: "English (Canada)" },
  { value: "en-GB", label: "English (UK)" },
  { value: "en-IN", label: "English (India)" },
  { value: "en-IE", label: "English (Ireland)" },
  { value: "en-NZ", label: "English (New Zealand)" },
  { value: "en-PH", label: "English (Philippines)" },
  { value: "en-SG", label: "English (Singapore)" },
  { value: "en-ZA", label: "English (South Africa)" },
  { value: "en-US", label: "English (US)" },
  { value: "et", label: "Estonian" },
  { value: "fi", label: "Finnish" },
  { value: "fr", label: "French" },
  { value: "fr-BE", label: "French (Belgium)" },
  { value: "fr-CA", label: "French (Canada)" },
  { value: "fr-FR", label: "French (France)" },
  { value: "fr-CH", label: "French (Switzerland)" },
  { value: "ka", label: "Georgian" },
  { value: "de", label: "German" },
  { value: "de-AT", label: "German (Austria)" },
  { value: "de-DE", label: "German (Germany)" },
  { value: "de-CH", label: "German (Switzerland)" },
  { value: "el", label: "Greek" },
  { value: "gu", label: "Gujarati" },
  { value: "he", label: "Hebrew" },
  { value: "hi", label: "Hindi" },
  { value: "hu", label: "Hungarian" },
  { value: "is", label: "Icelandic" },
  { value: "id", label: "Indonesian" },
  { value: "it", label: "Italian" },
  { value: "it-IT", label: "Italian (Italy)" },
  { value: "it-CH", label: "Italian (Switzerland)" },
  { value: "ja", label: "Japanese" },
  { value: "kn", label: "Kannada" },
  { value: "kk", label: "Kazakh" },
  { value: "km", label: "Khmer" },
  { value: "ko", label: "Korean" },
  { value: "lo", label: "Lao" },
  { value: "lv", label: "Latvian" },
  { value: "lt", label: "Lithuanian" },
  { value: "mk", label: "Macedonian" },
  { value: "ms", label: "Malay" },
  { value: "ml", label: "Malayalam" },
  { value: "mr", label: "Marathi" },
  { value: "mn", label: "Mongolian" },
  { value: "ne", label: "Nepali" },
  { value: "no", label: "Norwegian" },
  { value: "fa", label: "Persian" },
  { value: "pl", label: "Polish" },
  { value: "pt", label: "Portuguese" },
  { value: "pt-BR", label: "Portuguese (Brazil)" },
  { value: "pt-PT", label: "Portuguese (Portugal)" },
  { value: "pa", label: "Punjabi" },
  { value: "ro", label: "Romanian" },
  { value: "ru", label: "Russian" },
  { value: "sr", label: "Serbian" },
  { value: "si", label: "Sinhala" },
  { value: "sk", label: "Slovak" },
  { value: "sl", label: "Slovenian" },
  { value: "es", label: "Spanish" },
  { value: "es-AR", label: "Spanish (Argentina)" },
  { value: "es-BO", label: "Spanish (Bolivia)" },
  { value: "es-CL", label: "Spanish (Chile)" },
  { value: "es-CO", label: "Spanish (Colombia)" },
  { value: "es-CR", label: "Spanish (Costa Rica)" },
  { value: "es-DO", label: "Spanish (Dominican Republic)" },
  { value: "es-EC", label: "Spanish (Ecuador)" },
  { value: "es-SV", label: "Spanish (El Salvador)" },
  { value: "es-ES", label: "Spanish (Spain)" },
  { value: "es-GT", label: "Spanish (Guatemala)" },
  { value: "es-HN", label: "Spanish (Honduras)" },
  { value: "es-MX", label: "Spanish (Mexico)" },
  { value: "es-NI", label: "Spanish (Nicaragua)" },
  { value: "es-PA", label: "Spanish (Panama)" },
  { value: "es-PY", label: "Spanish (Paraguay)" },
  { value: "es-PE", label: "Spanish (Peru)" },
  { value: "es-PR", label: "Spanish (Puerto Rico)" },
  { value: "es-US", label: "Spanish (USA)" },
  { value: "es-UY", label: "Spanish (Uruguay)" },
  { value: "es-VE", label: "Spanish (Venezuela)" },
  { value: "sw", label: "Swahili" },
  { value: "sv", label: "Swedish" },
  { value: "ta", label: "Tamil" },
  { value: "te", label: "Telugu" },
  { value: "th", label: "Thai" },
  { value: "tr", label: "Turkish" },
  { value: "uk", label: "Ukrainian" },
  { value: "ur", label: "Urdu" },
  { value: "uz", label: "Uzbek" },
  { value: "vi", label: "Vietnamese" },
  { value: "cy", label: "Welsh" },
  { value: "zu", label: "Zulu" },
  // Philippines
  { value: "tl", label: "Tagalog" },
  { value: "fil", label: "Filipino" },
  { value: "taglish", label: "Taglish (Tagalog-English Mix)" },
  { value: "ceb", label: "Cebuano" },
  { value: "ilo", label: "Ilocano" },
  { value: "hil", label: "Hiligaynon" },
  { value: "war", label: "Waray" },
  { value: "pam", label: "Kapampangan" },
  { value: "pag", label: "Pangasinan" },
  { value: "bcl", label: "Bikol" },
  { value: "mrn", label: "Maranao" },
  { value: "mdh", label: "Maguindanao" },
  { value: "tsg", label: "Tausug" },
  // Belgium
  { value: "nl-BE", label: "Flemish (Belgium)" }, // Explicit label for Flemish preference
  { value: "wa", label: "Walloon" },
  { value: "lb", label: "Luxembourgish" },
  { value: "de-BE", label: "German (Belgium)" },
  { value: "li", label: "Limburgish" },
  { value: "vls", label: "West Flemish" },
  { value: "pcd", label: "Picard" },
  // Cameroon
  { value: "en-CM", label: "English (Cameroon)" },
  { value: "fr-CM", label: "French (Cameroon)" },
  { value: "wes", label: "Cameroonian Pidgin English" },
  { value: "camfranglais", label: "Camfranglais" },
  { value: "ewo", label: "Ewondo" },
  { value: "dua", label: "Duala" },
  { value: "bas", label: "Basaa" },
  { value: "ff-CM", label: "Fulfulde (Cameroon)" },
  { value: "bum", label: "Bulu" },
  { value: "bbj", label: "Ghomala'" },
  { value: "byv", label: "Medumba" },
].sort((a, b) => a.label.localeCompare(b.label));

export const SPEAKER_LANGUAGES = [
  { value: "auto", label: "Auto detect" },
  ...TARGET_LANGUAGES,
];
